### ISSUE TITLE
Orientar usuário no momento de login sem preencher formulário

### ISSUE THREAD

**Issue by joaoloboalmeida** [joaoloboalmeida/piFrontend#26]
Ao tentar logar sem preencher o formulário, aparece apenas uma mensagem de algo errado, porém não há nenhuma orientação do que deve ser feito. Implementar uma orientação que direcione o usuário ao que deve ser feito.

**Comment by RonaldoAzevedo** [comment]
Instruções implementadas

**Comment by pvinicius1337** [comment]
testado e funcionando
